In [1]:
a=20
a

20

In [2]:
a=30
b=50
a
b

50

In [3]:
a=[23,45,67,89]
a

[23, 45, 67, 89]

In [4]:
import numpy as np
score=np.array(a)
score

array([23, 45, 67, 89])

In [5]:
d=np.mean(score)
d

np.float64(56.0)

In [6]:
print(np.max(score))

89


In [7]:
print(np.min(score))

23


In [9]:
f=np.zeros([2,4])
f

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [10]:
s=np.random.rand(4,3)
s

array([[0.48733883, 0.67896756, 0.00614447],
       [0.95755918, 0.34786527, 0.20519555],
       [0.2315405 , 0.02922511, 0.66673342],
       [0.44776198, 0.36497386, 0.77343075]])

In [11]:
g=np.ones([3,3])
g

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [15]:
n=np.array([23,45,66,1,2,99,11,12,45,34,65,78,55,10,55,98])
d=np.reshape(n,(2,8))
d

array([[23, 45, 66,  1,  2, 99, 11, 12],
       [45, 34, 65, 78, 55, 10, 55, 98]])

In [17]:
a=np.arange(16).reshape(4,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [18]:
b=np.array([1,2,3,4,5,6,7,8,9,21,34])
c=b[2:4]
c

array([3, 4])

In [19]:
a=np.array([4,5,6])
c=np.array([2,3,4])
a+c

array([ 6,  8, 10])

In [20]:
a=np.array([1,2,3])
b=np.array([7,8,9])
a-b

array([-6, -6, -6])

In [21]:
a=np.array([1,2,3])
c=np.array([4,5,6])
a*c

array([ 4, 10, 18])

In [25]:
a=np.array([[6,7,8],[4,5,6]])
b=np.array([[2,4],
            [4,5],
            [6,7]])
c=np.dot(a,b)
c
           

array([[ 88, 115],
       [ 64,  83]])

In [26]:
mat=np.array([[2,3,5],[7,8,9]])
print(mat.T)

[[2 7]
 [3 8]
 [5 9]]


In [27]:
arr=np.array([3,8,9,5,4])
print(np.sort(arr))

[3 4 5 8 9]


In [28]:
a=np.array([4,6,0])
b=np.array([3,0,8])
print(np.concatenate((a,b)))

[4 6 0 3 0 8]


In [29]:
arr=np.array([1,2,4,8,6,5,5])
a=np.unique(arr)
a

array([1, 2, 4, 5, 6, 8])

In [30]:
print(np.eye(5))


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [33]:
arr=np.linspace(2,4,5)