In [4]:
import numpy as np
a=np.array([1,2,3,5,4])
print(np.argmax(a))

3


In [3]:
print(np.argmin(a))

0


In [5]:
print(np.where(a>3))

(array([3, 4]),)


In [6]:
print(np.cumsum(a))

[ 1  3  6 11 15]


In [7]:
a=np.random.randint(1,10,10)
print(a)

[7 9 5 8 8 8 7 7 6 1]


In [10]:
a=np.array([6,7,8,9,0])
b=np.array([1,2,3,4,5])
print(np.corrcoef(a,b))

[[ 1.        -0.4472136]
 [-0.4472136  1.       ]]


In [11]:
a=np.array([0,9,8,7,6])
np.save("ps.npy",a)
print(np.load("ps.npy"))

[0 9 8 7 6]


In [13]:
a=np.array([6,4,0,9,8])
print(a[2:4])

[0 9]


In [14]:
print(a[:2])


[6 4]


In [15]:
print(a[:-2])

[6 4 0]


In [16]:
print(a[-2:])

[9 8]


In [19]:
arr=np.array([[1,2,3,4],[5,6,7,8],[4,0,8,7]])
print(arr[0:1,1:3])

[[2 3]]


In [20]:
print(arr[:,::3])

[[1 4]
 [5 8]
 [4 7]]


In [21]:
print(arr[:,1:2])

[[2]
 [6]
 [0]]


<class 'NameError'>: name 'pd' is not defined

In [2]:
import pandas as pd

df = pd.read_csv("housing.csv.zip", compression="zip")
df.head()

<class 'FileNotFoundError'>: [Errno 44] No such file or directory: 'housing.csv.zip'